---
# --------------------------------

- name: '{{user.name}} : get user status (CM=F)'
  getent:
    database: passwd
    fail_key: false
    key: '{{user.name}}'
  register: reg_user
  check_mode: false
  changed_when: false
  tags: ct-user

- name: '{{user.name}} : record user status and mortality (CM=F)'
  set_fact:
    user_exists: '{{reg_user.msg is not defined}}'
    mortal: '{{user.mortal | bool}}'
  check_mode: false
  tags: ct-user

- name: '{{user.name}} : report on user status (CM=F)'
  debug:
    var: reg_user
    verbosity: 1
  check_mode: false
  tags: [ct-user]

- name: '{{user.name}} : if adding user, add user group first'
  group:
    name: '{{user.name}}'
    state: present
  become: true
  when:
  - mortal
  - user.state == 'present'
  tags: ct-user

- name: '{{user.name}} : if removing user, remove SSH keys first'
  authorized_key:
    key: '{{kk.key}}'
    state: absent
    user: '{{user.name}}'
  loop: '{{user.ssh_keys}}'
  loop_control:
    loop_var: kk
    label: '{{user.name}}'
  ignore_errors: '{{ansible_check_mode|bool}}'
  when:
  - mortal
  - user_exists
  - user.state == 'absent'
  - user.ssh_keys is defined
  become: true
  tags: ct-user

- name: '{{user.name}} : user account'
  user:
    name: '{{user.name}}'
    comment: '{{user.comment}}'
    groups: "{{(user.groups + [user.name]) | join(',')}}"
    append: true
    shell: /bin/bash
    password: '{{user.password | default(omit)}}'
    state: '{{user.state}}'
  when: mortal
  become: true
  tags: ct-user

- name: '{{user.name}} : if removing user, remove user group afterwards'
  group:
    name: '{{user.name}}'
    state: absent
  become: true
  when:
  - mortal
  - user.state == 'absent'
  tags: ct-user

- name: '{{user.name}} : get user status (CM=F)'
  getent:
    database: passwd
    fail_key: false
    key: '{{user.name}}'
  register: reg_user
  check_mode: false
  changed_when: false
  tags: [ct-user]

- name: '{{user.name}} : record user status (CM=F)'
  set_fact:
    user_exists: '{{reg_user.msg is not defined}}'
  check_mode: false
  tags: ct-user

- name: '{{user.name}} : report on user status (CM=F)'
  debug:
    var: reg_user
    verbosity: 1
  check_mode: false
  tags: [ct-user]

- name: '{{user.name}} : create home directory structure'
  file:
    path: '{{ct_user_homedir}}/{{user.name}}/{{kk.name}}'
    state: directory
    owner: '{{user.name}}'
    group: '{{user.name}}'
    mode: '{{kk.mode}}'
  loop:
  - {name: .ssh, mode: '0700'}
  - {name: .ssh/cfg.d, mode: '0700'}
  - {name: .ssh/keys, mode: '0700'}
  - {name: .vim, mode: '0755'}
  - {name: .vim/ftplugin, mode: '0755'}
  - {name: bin, mode: '0755'}
  - {name: etc, mode: '0755'}
  - {name: etc/bash.d, mode: '0755'}
  - {name: etc/handy.d, mode: '0755'}
  - {name: etc/misc, mode: '0755'}
  - {name: src, mode: '0755'}
  - {name: tmp, mode: '0755'}
  - {name: var, mode: '0755'}
  - {name: var/log, mode: '0755'}
  - {name: work, mode: '0755'}
  loop_control:
    loop_var: kk
    label: '{{kk.name}}'
  when:
  - (not mortal) or (mortal and user.state == 'present')
  become: true
  tags: [ct-user]

- name: '{{user.name}} : manage SSH keys'
  authorized_key:
    key: '{{kk.key}}'
    state: '{{kk.state}}'
    user: '{{user.name}}'
  loop: '{{user.ssh_keys}}'
  loop_control:
    loop_var: kk
    label: '{{user.name}}'
  ignore_errors: '{{ansible_check_mode|bool}}'
  when:
  - user.state == 'present'
  - user.ssh_keys is defined
  become: true
  tags: [ct-user]

- name: '{{user.name}} : copy over base fragment for SSH config'
  copy:
    src: ssh_first.cfg
    dest: '{{ct_user_homedir}}/{{user.name}}/.ssh/cfg.d/000.cfg'
    owner: '{{user.name}}'
    group: '{{user.name}}'
    mode: '0600'
  when:
  - mortal
  - user.state == 'present'
  become: true
  tags: ct-user

- name: '{{user.name}} : add line to .bashrc'
  lineinfile:
    dest: '{{ct_user_homedir}}/{{user.name}}/.bashrc'
    group: '{{user.name}}'
    line: '[[ -d ~/etc/bash.d ]] && for ff in ~/etc/bash.d/*.sh; do source $ff; done # ansible'
    owner: '{{user.name}}'
    state: present
  when:
  - (not mortal) or (mortal and user.state == 'present')
  become: true
  tags: ct-user

- name: '{{user.name}} : copy misc files over'
  copy:
    dest: '{{kk.dest}}'
    group: '{{user.name}}'
    mode: '{{kk.mode}}'
    owner: '{{user.name}}'
    src: '{{kk.src}}'
  loop:
  - {src: dot_yamllint, dest: '{{ct_user_homedir}}/{{user.name}}/.yamllint', mode: '0644'}
  - {src: dot_vimrc, dest: '{{ct_user_homedir}}/{{user.name}}/.vimrc', mode: '0444'}
  - {src: yaml.vim, dest: '{{ct_user_homedir}}/{{user.name}}/.vim/ftplugin/', mode: '0444'}
  loop_control:
    loop_var: kk
    label: '{{kk.dest}}'
  when:
  - (not mortal) or (mortal and user.state == 'present')
  become: true
  tags: ct-user

- name: '{{user.name}} : sort out prompt string'
  template:
    src: ps1.sh.j2
    dest: '{{ct_user_homedir}}/{{user.name}}/etc/bash.d/ps1.sh'
    owner: '{{user.name}}'
    group: '{{user.name}}'
    mode: '0444'
  when:
  - (not mortal) or (mortal and user.state == 'present')
  become: true
  tags: ct-user

- name: '{{user.name}} : assemble SSH config fragments'
  assemble:
    delimiter: '# --------------------------------'
    dest: '{{ct_user_homedir}}/{{user.name}}/.ssh/config'
    group: '{{user.name}}'
    regexp: '\w+\.cfg'
    mode: '0600'
    owner: '{{user.name}}'
    src: '{{ct_user_homedir}}/{{user.name}}/.ssh/cfg.d/'
  when:
  - mortal
  - user.state == 'present'
  - user.assemble_ssh | default(false)
  become: true
  tags: ct-user

- name: '{{user.name}} : create extra dirs from ct_user_extra_dirs'
  file:
    group: '{{user.name}}'
    mode: '{{kk.mode}}'
    owner: '{{user.name}}'
    path: '{{kk.path}}'
    state: directory
  loop: '{{ct_user_extra_dirs}}'
  loop_control:
    loop_var: kk
  when:
  - (not mortal) or (mortal and user.state == 'present')
  become: true
  tags: ct-user

# --------------------------------
...
